# Custom Language File for Launcher Customizer

[ejs.app]
title = "Hunger Games Luncher"

[ejs.landing]
mediaGitHubURL = "https://github.com/IvnoGood/HungerGamesLuncher"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "https://youtube.com/@fonfdrag?si=1IUiIGqDwuc3VaBf"
mediaDiscordURL = "https://discord.gg/pHT3UpXmkg"

[ejs.settings]
sourceGithubLink = "https://github.com/dscalZi/HeliosLauncher"
supportLink = "https://github.com/dscalZi/HeliosLauncher/issues"

[ejs.welcome]
welcomeHeader = "WELCOME TO THE HUNGER GAMES ADVENTURE"
welcomeDescription = "Enter the thrilling world of Minecraft Hunger Games, where players are dropped into a vast arena filled with challenges and dangers. Compete against others in a fight for survival, scavenging for resources, weapons, and food to outlast your opponents. Strategize your moves, form alliances, or go solo as you navigate treacherous terrains and defeat rivals. Only the strongest and most cunning will emerge victorious in this ultimate test of skill and survival. Will you be the last one standing? Join the battle and find out!"
welcomeDescCTA = "You are just a few clicks away from the thriling Hunger Games Adventure."
